#!/usr/bin/env python3
"""Produce self-hosted WOFF2 shards, preserving every source-font character.

Usage: python3 scripts/build_garden_fonts.py /path/to/font-sources
Requires fonttools[woff]. Ordinary poetry/blog edits do NOT require rebuilding.
The source directory must contain qiji.ttf, ZhuqueFangsong-Regular.ttf,
qiji-LICENSE.txt and zhuque-LICENSE.txt (see docs/WRITING.md).
"""
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
import argparse
import json
import shutil

from fontTools import subset
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
DEST = ROOT / "assets/fonts/garden"


def unicode_ranges(points):
    spans = []
    for point in sorted(points):
        if spans and spans[-1][1] + 1 == point:
            spans[-1][1] = point
        else:
            spans.append([point, point])
    return ",".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in spans)


def make_shard(job):
    source, family, slug, name, points = job
    font = TTFont(source, recalcTimestamp=False)
    opts = subset.Options()
    opts.drop_tables += ["FFTM"]
    opts.flavor = "woff2"
    opts.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
    opts.name_legacy = True
    opts.name_languages = ["*"]
    subsetter = subset.Subsetter(options=opts)
    subsetter.populate(unicodes=points)
    subsetter.subset(font)
    # Derived web fonts use new names, respecting upstream Reserved Font Names.
    for record in font["name"].names:
        if record.nameID in (1, 4, 16):
            record.string = family.encode(record.getEncoding())
        elif record.nameID == 6:
            record.string = family.replace(" ", "").encode(record.getEncoding())
        elif record.nameID == 3:
            record.string = (family + ";web-1").encode(record.getEncoding())
    font.flavor = "woff2"
    filename = f"{slug}-{name}.woff2"
    font.save(DEST / filename)
    font.close()
    css = ("@font-face {\n"
           f"  font-family: '{family}';\n"
           f"  src: url('./{filename}') format('woff2');\n"
           "  font-weight: 400; font-style: normal; font-display: swap;\n"
           f"  unicode-range: {unicode_ranges(points)};\n"
           "}\n")
    return css, {"file": filename, "characters": len(points), "bytes": (DEST / filename).stat().st_size}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    args = parser.parse_args()
    DEST.mkdir(parents=True, exist_ok=True)
    core = set(range(32, 127))
    for folder in ("_data", "_includes", "_pages", "_publications"):
        for path in (ROOT / folder).rglob("*"):
            if path.is_file():
                core.update(map(ord, path.read_text()))
    core.update(map(ord, (ROOT / "_config.yml").read_text()))
    jobs = []
    manifest = {}
    for slug, source, family in (("qiji", "qiji.ttf", "Garden Qiji"),
                                 ("zhuque", "ZhuqueFangsong-Regular.ttf", "Garden Zhuque")):
        path = args.source / source
        with TTFont(path) as font:
            supported = set(font.getBestCmap())
        buckets = {"core": supported & core}
        for point in sorted(supported - core):
            key = f"{point // 256:04x}"
            buckets.setdefault(key, set()).add(point)
        for name, points in buckets.items():
            jobs.append((str(path), family, slug, name, sorted(points)))
        manifest[slug] = {"source_characters": len(supported), "shards": len(buckets)}
        shutil.copyfile(args.source / f"{slug}-LICENSE.txt", DEST / f"{slug}-LICENSE.txt")
    with ProcessPoolExecutor(max_workers=4) as pool:
        results = list(pool.map(make_shard, jobs))
    (DEST / "fonts.css").write_text("/* Generated by scripts/build_garden_fonts.py. */\n" + "\n".join(css for css, _ in results))
    manifest["files"] = [info for _, info in results]
    (DEST / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    print(json.dumps({"fonts": {k: v for k, v in manifest.items() if k != "files"},
                      "total_bytes": sum(i["bytes"] for i in manifest["files"])}, indent=2))


if __name__ == "__main__":
    main()
